### ISSUE TITLE
error from pharokka input: `ValueError: invalid literal for int() with base 10: 'No_PHROGs_HMM'`

### ISSUE THREAD

**Issue by GeoMicroSoares** [susiegriggo/Phynteny#16]
Hi @susiegriggo @Vini2 @gbouras13 - thanks so much for developing this cool piece of software!

I'm having trouble with some pharokka-generated input - as I submit the resulting GBK to phynteny, I get the following error message:
```
/home/andre/miniconda3/envs/phynteny/bin/phynteny:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
2024-11-28 08:40:27.988 | INFO     | __main__:main:65 - Starting Phynteny
2024-11-28 08:40:27.988 | INFO     | __main__:main:71 - PHROG integer information located at: /home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/phynteny_utils/phrog_annotation_info/phrog_integer.pkl
2024-11-28 08:40:27.988 | INFO     | __main__:main:75 - PHROG category information located at: /home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/phynteny_utils/phrog_annotation_info/integer_category.pkl
2024-11-28 08:40:27.988 | INFO     | phynteny_utils.format_data:get_dict:55 - dictionary loaded from /home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/phynteny_utils/phrog_annotation_info/integer_category.pkl
2024-11-28 08:40:28.003 | INFO     | phynteny_utils.format_data:get_dict:55 - dictionary loaded from /home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/phynteny_utils/phrog_annotation_info/phrog_integer.pkl
2024-11-28 08:40:28.003 | INFO     | __main__:main:80 - Reading genbank file!
2024-11-28 08:40:28.020300: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-28 08:40:39.115 | INFO     | __main__:main:93 - Confidence object located at /home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/phynteny_utils/phrog_annotation_info/confidence_kde.pkl
Annotating the phage: Achnantidium_ExStream_22_8_230524_1008|provirus_5316999_5334483
Traceback (most recent call last):
  File "/home/andre/miniconda3/envs/phynteny/bin/phynteny", line 120, in <module>
    main()
  File "/home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/andre/miniconda3/envs/phynteny/bin/phynteny", line 95, in main
    phynteny_dict = predictor.run_phynteny(
  File "/home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/phynteny_utils/predictor.py", line 85, in run_phynteny
    phages[key]["phrogs"] = [
  File "/home/andre/miniconda3/envs/phynteny/lib/python3.10/site-packages/phynteny_utils/predictor.py", line 86, in <listcomp>
    0 if i in ["No_PHROG", "vfdb", "acr", "card", "defensefinder"] else int(i) for i in phages[key]["phrogs"]
ValueError: invalid literal for int() with base 10: 'No_PHROGs_HMM'
```

Is this something you've seen before? I can provide more data if needed but here's the versions I'm running:

```
$ phynteny --version
/home/andre/miniconda3/envs/phynteny/bin/phynteny:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
phynteny, version 0
```
I've made sure manually to get phynteny to 0.1.13.

```
$ pharokka.py --version
1.7.4
```

pharokka was ran as follows: `pharokka.py -i $i -o ${name}_pharokka -t 10 --fast -f -p ${name} -d pharokka_db_271124/`
and phynteny as follows: `phynteny $i -o ${name}_phynteny -m phynteny_models_271124/`

Thanks in advance for any help - I'm trying to follow your instructions as best as possible but really can't figure a way out of this!

**Comment by gbouras13** [comment]
Hi @GeoMicroSoares ,

I think the cause of this issue is `--fast` in Pharokka. Let me know, but that should solve the issue. We are currently updating our entire annotation software stack, so we will fix this issue soon.

George

**Comment by GeoMicroSoares** [comment]
Hi there - indeed that was it! Thank you very much :D
